- name: Configure secure nginx
  hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - name: Set nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Copy ssl cert
      copy:
        src: ssl/nginx.crt
        dest: "{{ ssl_cert_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Copy ssl key
      copy:
        src: ssl/nginx.key
        dest: "{{ ssl_key_path }}"
        owner: root
        group: root
        mode: 0600

    - name: Copy index.html
      copy:
        src: html/index.html
        dest: "{{ web_root }}/index.html"
        mode: 0644

    - name: Config nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644

    - name: Ensure nginx is running
      service:
        name: nginx
        state: restarted
        enabled: true

    - name: Check 443 port access
      uri:
        url: https://localhost
        validate_certs: no
        status_code: 200
